### ISSUE TITLE
Implement UART

### ISSUE THREAD

**Issue by flaviut** [d16-processor/d16i#2]
See [d16 reference manual][], §4.1 "UART" for the implementation specification.

[d16 reference manual]: https://github.com/d16-processor/d16/blob/master/doc/D16%20Reference%20Manual.pdf

**Comment by flaviut** [comment]
I'll get this done by friday night.

**Comment by flaviut** [comment]
Ok, so this is taking a lot longer than I expected. Here are the components that must be implemented for this to work:

- Non-blocking read from stdin seems to be very difficult, at least in a portable way. The fix is to have a thread to do the reading, but killing the thread is very difficult, as it is impossible to know when the `read()` call will return.
- The UART needs to store state in the CPU, for both the FIFO buffers and to keep track of how much time has passed since IO functions were last called. 
  - To be clear, this time isn't wall clock time, it's based on the number of instructions executed.
  - This is hard to do because it introduces circular dependencies between the CPU and UART system.
- Calling the IO functions seems to work fine, although it might belong better in `execute_instruction()` rather than `load_*`, `store_*`.

**Comment by C-Elegans** [comment]
The reason they were in load* and store* was so that cpu load and store logic did not need to be modified to add the io functions. In the actual cpu implementation, the peripherals and memory will be managed by either the memory controller or a new bus controller.
